### ISSUE TITLE
Assembly.GetEntryAssembly is not accurate, and Assembly.GetCallingAssembly does not work as expected.

### ISSUE THREAD

**Issue by bensmith009988** [TinyBlueRobots/Serilog.Enrichers.AssemblyName#7]
I wanted to point this out for anyone using this package, or get corrected if I am mistaken. 

Assembly.GetEntryAssembly, (The primary method that this enricher is using to populate the "Assembly__" properties through enrichment), is not always accurate. When the context of the application changes assemblies, and logs are fired off in a different assembly, the first assembly of the executing operation is populated for all logs, by design. To me, this doesn't seem like a great solution to needing an accurate assembly enricher in my application logs. Some of my logs have inaccurate assemblies. I will admit, however, this is not fault of the enricher here, and it is better than nothing. At least the assembly that is populated through log enrichment, when it is not entirely accurate, is still at least a related assembly (It is always the original executing assembly in the chain of events). 

The Assembly.GetCallingAssembly returns completely inaccurate assembly information, and defaults always to the assembly of the configuration part of your logging project (depending on each implementation). I would vote to remove any logic in this Nuget package that relies on that method and replace simply with "UnknownAssembly" as the value populated when GetEntryAssembly returns null.

There are other ways to get an accurate assembly reading but it involves a lot of work around and cannot be added through an enricher in Serilog. Did I miss something? Am I mistaken in my conclusions? I think knowing this upfront as a disclaimer would have saved me a lot of time, maybe others.

**Comment by warmfire540** [comment]
the Assembly is wonky for me depending on if it's a web app or service etc.
I may have to change my setup to manually pass the assembly which I'd rather not...
